# Generated by Django 4.1.1 on 2022-09-06 19:53

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Choice = apps.get_model('polls', 'Choice')
    LongChoice = apps.get_model('polls', 'LongChoice')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(Choice)
    Choice.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)

    new_ct2 = ContentType.objects.get_for_model(LongChoice)
    LongChoice.objects.all().update(polymorphic_ctype=new_ct2)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('polls', '0004_choicepoly_longchoicepoly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='longchoice',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='choice',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
